datasource:
  username: 'example'
  password: 'example'
  host: 'localhost'
  port: 5432
  database: 'git_repository'

rabbitmq:
  host: '127.0.0.1'
  port: 5672
  username: 'example'
  password: 'example'