datasource:
  username: 'example'
  password: 'example'
  host: 'git_data_db'
  port: 5432
  database: 'git_repository'

rabbitmq:
  host: 'rabbitmq'
  port: 5672
  username: 'example'
  password: 'example'