services:
  database:
    image: postgres:15-alpine
    container_name: database
    restart: always
    build:
      context: ./modules/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: git_repository
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 6432:5432

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    network_mode: "host"
    ports:
      - 5672:5672
      - 15672:15672

  szzwebserver:
    image: szzwebserver
    container_name: szzwebserver 
    pull_policy: never
    network_mode: "host"
    build:
      context: ./modules/webserver
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    
volumes:
  pgdata:
    



